### ISSUE TITLE
websocket futures.order_book的问题

### ISSUE THREAD

**Issue by imskin** [gateio/gateapi-php#2]
event
update/all

{
    "channel":"futures.order_book",
    "event":"all",
    "time":1541500161,
    "result":{
        "contract":"BTC_USD",
        "asks":[
            {"p":"97.1","s":2245}, // p: price, s: size
            {"p":"97.1","s":2245},
            {"p":"97.1","s":2245}
        ],
        "bids":[
            {"p":"97.1","s":2245},
            {"p":"97.1","s":2245},
            {"p":"97.1","s":2245}
        ]
    }
}

Or:

{
    "channel":"futures.order_book",
    "event":"update",
    "time":1541500167,
    "result":[{
        "p":"97.5",
        "s":6541,  // +-   asks:- bids:+
        "c":"BTC_USD",  // p: price, s: size , c contract
        "id":93973512
    },]
}

update是对上一次all的更新  
s为正时更改bids对应p的数量,如果p不存在,则插入此p. s为负则更改asks

当s为0时,需要移除此p 这个p可能是bids也可能是asks

这个理解对吗

另外id起什么作用

**Comment by revilwang** [comment]
是的，就是这么个意思

id用于标识每个独立的请求
