### ISSUE TITLE
合约交易 WebSocket API 触发强平

### ISSUE THREAD

**Issue by imskin** [gateio/gateapi-php#3]
触发到强平的时候   请问 WebSocket是通过哪个订阅通知的    用什么字段判断呢

**Comment by revilwang** [comment]
通过订阅 `futures.liquidates` 来获取后续的通知，订阅时指定关注的 contract 

详细字段说明可以参阅合约 WebSocket 文档 Liquidations API 章节：
https://www.gate.io/docs/futures/ws/index.html#liquidates-api
https://www.gateio.life/docs/futures/ws/index.html#liquidates-api

**Comment by imskin** [comment]
futures.liquidates   是在强平时才推送吗 平时不推的

**Comment by revilwang** [comment]
是这样的，强平时才推送
