### ISSUE TITLE
为什么官网上现货只有现货V2文档，V4只有期货。V4的现货文档再哪里？

### ISSUE THREAD

**Issue by zhouaini528** [gateio/gateapi-php#7]
如题

**Comment by revilwang** [comment]
v4 的文档正在准备入口，可以先直接访问这里 https://www.gatecn.io/docs/apiv4/zh_CN/index.html#gate-api-v4 查看

English version: https://www.gatecn.io/docs/apiv4/en/index.html#gate-api-v4

**Comment by zhouaini528** [comment]
很好很强大
