### ISSUE TITLE
FuturesTicker Mid, Bid, Ask Prices

### ISSUE THREAD

**Issue by dextervip** [gateio/gateapi-php#8]
Hello,

It would be nice if I have also the mid, highest bid, and lowest ask price for a future ticker without having to call order book such as in BitMEX API(https://www.bitmex.com/api/explorer/#!/Instrument/Instrument_get)

Best regards

**Comment by revilwang** [comment]
It is recommended to use WebSocket to retrieve best ask and bid price. We published a new channel `futures.book_ticker` yesterday to push best ask and bid price in realtime. Rest API responses are generally cached for performance's sake.
